<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <!-- Size optimization -->
    <TrimMode>partial</TrimMode>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishTrimmed>true</PublishTrimmed>
    <PublishReadyToRun>false</PublishReadyToRun>
    <DebugType>none</DebugType>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>

    <!-- Globalization/Resource optimizations -->
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <RuntimeHostConfigurationOption Include="System.Globalization.Invariant" Value="true" />
    <ProjectReference Include="..\Polarion\Polarion.csproj" />
  </ItemGroup>

  <ItemGroup>    
    <TrimmerRootAssembly Include="ReverseMarkdown" />
    <TrimmerRootAssembly Include="AngleSharp" />
    <TrimmerRootAssembly Include="Polarion" />
  </ItemGroup>

</Project>
