<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsTrimmable>true</IsTrimmable>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <TrimMode>partial</TrimMode>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>


    <!-- Package Metadata -->
    <PackageId>Polarion</PackageId>
    <Version>0.3.9</Version>
    <Authors>Todd Schavey</Authors>
    <Company>Peakflames</Company>
    <Description>A C# package to access the Polarion WSDL API. Complete API documentation available at: https://github.com/peakflames/PolarionApiClient/blob/main/api.md</Description>
    <PackageTags>polarion;polaron-alm;markdown</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/peakflames/PolarionApiClient</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>

    <!-- Source Link -->
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>

    <!-- Workaround for IDE0005: removed unused directives, we must enable XML
         documentation and ignore the warning it generates (CS1591) -->
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>CS8981,CS1591,IL2026,IL2104</NoWarn>
    <AnalysisLevel>10.0</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentResults" Version="4.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.2" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.2" />
    <PackageReference Include="System.ServiceModel.Http" Version="8.1.2" />
    <PackageReference Include="System.ServiceModel.Primitives" Version="8.1.2" />
    <PackageReference Include="System.ServiceModel.Security" Version="6.0.0" />
    <PackageReference Include="ReverseMarkdown" Version="6.2.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    <None Include="..\..\api.md" Pack="true" PackagePath="\" />
    <!-- <EmbeddedResource Include="TrimmerRoots.xml" /> -->
  </ItemGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="ReverseMarkdown" />
    <TrimmerRootAssembly Include="AngleSharp" />
    <TrimmerRootAssembly Include="Polarion" />
  </ItemGroup>

</Project>
